### ISSUE TITLE
peaks: Wrong BED format for identified cross-linked sites

### ISSUE THREAD

**Issue by nebo56** [tomazc/iCount#122]
- **inconsistent BED format** after _iCount peaks_ method
Strand information should be in the 6th column and not duplicated in 5th and 7th. I think this might be a problem with the last bedtools update.
example : 
chr1    15005   15006   WASH7P - WASH7P 1       -
chr1    15006   15007   WASH7P - WASH7P 2       -
chr1    16477   16478   WASH7P - WASH7P 1       -

**Comment by JureZmrzlikar** [comment]
Inconsistent BED format:
The output file is tab separated, so there are only 6 columns:
4-th column: "WASH7P - WASH7P", 
5-th column: "1"
6-th column: "-"

Why the strange shape of the 4th column? I am not 99% sure, but I think this was the logic... Genes are not unique identifiers (Different genes can have same name) but gene-ID's are. But putting gene-ID's in the resulting BED file is unpractical - as a biologist / bioinformatician you want the gene name. The solution was to provide the 4th column of type:
 `gene_id1, gene_id2, gene_id3 - gene_name1, gene_name2, gene_name3`. 
If it solves the problem, we can just use different delimiter between gene_id's and gene name's. Or we can somehow make the whole field as one word, to not confuse the parser with whitespaces:
 `gene_id1,gene_id2,gene_id3-gene_name1,gene_name2,gene_name3`
