### ISSUE TITLE
genome: Specify chromosome

### ISSUE THREAD

**Issue by Faitero** [tomazc/iCount#123]
iCount genome mus_musculus -r 80 --chromosomes 21 MT
Executing the following command: iCount genome mus_musculus -r 80 --chromosomes 21 MT
Input parameters for function 'genome' in iCount.genomes.ensembl
    species: mus_musculus
    release: 80
    out_dir: None
    genome: None
    chromosomes: ['21', 'MT']
Input parameters for function 'species' in iCount.genomes.ensembl
    release: 84
There are 70 species available: ailuropoda_melanoleuca,anas_platyrhynchos,ancestral_alleles,anolis_carolinensis,astyanax_mexicanus,bos_taurus,caenorhabditis_elegans,callithrix_jacchus,canis_familiaris,cavia_porcellus,chlorocebus_sabaeus,choloepus_hoffmanni,ciona_intestinalis,ciona_savignyi,danio_rerio,dasypus_novemcinctus,dipodomys_ordii,drosophila_melanogaster,echinops_telfairi,equus_caballus,erinaceus_europaeus,felis_catus,ficedula_albicollis,gadus_morhua,gallus_gallus,gasterosteus_aculeatus,gorilla_gorilla,homo_sapiens,ictidomys_tridecemlineatus,latimeria_chalumnae,lepisosteus_oculatus,loxodonta_africana,macaca_mulatta,macropus_eugenii,meleagris_gallopavo,microcebus_murinus,monodelphis_domestica,mus_musculus,mustela_putorius_furo,myotis_lucifugus,nomascus_leucogenys,ochotona_princeps,oreochromis_niloticus,ornithorhynchus_anatinus,oryctolagus_cuniculus,oryzias_latipes,otolemur_garnettii,ovis_aries,pan_troglodytes,papio_anubis,pelodiscus_sinensis,petromyzon_marinus,poecilia_formosa,pongo_abelii,procavia_capensis,pteropus_vampyrus,rattus_norvegicus,saccharomyces_cerevisiae,sarcophilus_harrisii,sorex_araneus,sus_scrofa,taeniopygia_guttata,takifugu_rubripes,tarsius_syrichta,tetraodon_nigroviridis,tupaia_belangeri,tursiops_truncatus,vicugna_pacos,xenopus_tropicalis,xiphophorus_maculatus
[ValueError] Could not find file with chromosome 21.
  File "/Users/mozosi/Programs/ENV/env_iCount/lib/python3.5/site-packages/iCount-2.0.0.dev0-py3.5.egg/iCount/cli.py", line 438, in main
    result_object = func(**args)

  File "/Users/mozosi/Programs/ENV/env_iCount/lib/python3.5/site-packages/iCount-2.0.0.dev0-py3.5.egg/iCount/genomes/ensembl.py", line 323, in genome
    raise ValueError('Could not find file with chromosome {}.'.format(chromosome))

**Comment by JureZmrzlikar** [comment]
This is failing since there is no 21-th chromosome. You can check the available ones here:
ftp://ftp.ensembl.org/pub/release-80/fasta/mus_musculus/dna/
