### ISSUE TITLE
segment: Add suport for GENCODE annotation

### ISSUE THREAD

**Issue by tomazc** [tomazc/iCount#125]
- **extra feature** for _iCount segment_ - adding GENCODE annotation
example: [GRCh38.p7](https://www.gencodegenes.org/releases/current.html)

**Comment by JureZmrzlikar** [comment]
["The default human and mouse gene sets in the Ensembl browser is therefore also the current version of GENCODE"](http://www.ensembl.org/Help/Faq?id=303)

It this is true, this could probably be done quite fast...

**Comment by nebo56** [comment]
I tried it with the GENCODE annotation and I received the following error. Should I be using a different  bedtools version? Mine is: bedtools v2.17.0.

`iCount segment gencode.v26.annotation.gtf.gz gencode.v26.annotation.seg.gtf.gz GRCm38.p4.genome.fa.fai`

Executing the following command: iCount segment gencode.v26.annotation.gtf.gz gencode.v26.annotation.seg.gtf.gz GRCm38.p4.genome.fa.fai
Input parameters for function 'get_regions' in iCount.genomes.segment
    annotation: gencode.v26.annotation.gtf.gz
    segmentation: gencode.v26.annotation.seg.gtf.gz
    fai: GRCm38.p4.genome.fa.fai
    report_progress: False
Calculating intergenic regions...

[BEDToolsError] bedtools sort -i /tmp/pybedtools.cdjcu1fn.tmp -faidx /tmp/tmp01h7rroi
  File "/home/skgthab/programs/iCount2/iCount-master/iCount/cli.py", line 437, in main
    result_object = func(**args)
  File "/home/skgthab/programs/iCount2/iCount-master/iCount/genomes/segment.py", line 727, in get_regions
    intergenic_pos = _complement(gtf.fn, fai, '+')
  File "/home/skgthab/programs/iCount2/iCount-master/iCount/genomes/segment.py", line 518, in _complement
    gtf_sorted = gtf_strand_only.sort(faidx=genome_file).saveas()
  File "/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/bedtool.py", line 775, in decorated
    result = method(self, *args, **kwargs)
  File "/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/bedtool.py", line 337, in wrapped
    decode_output=decode_output,
  File "/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/helpers.py", line 356, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)

**Comment by JureZmrzlikar** [comment]
Check output of `bedtools sort --help`. If `-faidx` parameter is not listed in hep text, you should upgrade. I think this is the case, but check anyway.

**Comment by nebo56** [comment]
I sort it out with the last version of bedtools but now I'm receiving
another error when I run the segmentation command: [OSError] 28, which we
already resolved before by changing the temp folder. So far I tried to
change it like this:
- changing the TMP variable to a different directory:
ICOUNT_TMP_ROOT=/SAN/neuroscience/TE/Nejc/TMP
- and also by changing the "__init__.py" from  TMP_ROOT =
os.environ.get('ICOUNT_TMP_ROOT', '/tmp/iCount') to TMP_ROOT =
os.environ.get('ICOUNT_TMP_ROOT','/SAN/neuroscience/TE/Nejc/TMP')

Any idea what else I could do, there is a lot of FREE space in that folder:

$ iCount segment gencode.v26.annotation.gtf.gz
gencode.v26.annotation.seg.gtf.gz GRCm38.p4.genome.fa.fai
Executing the following command: iCount segment
gencode.v26.annotation.gtf.gz gencode.v26.annotation.seg.gtf.gz
GRCm38.p4.genome.fa.fai
Input parameters for function 'get_regions' in iCount.genomes.segment
    annotation: gencode.v26.annotation.gtf.gz
    segmentation: gencode.v26.annotation.seg.gtf.gz
    fai: GRCm38.p4.genome.fa.fai
    report_progress: False
Calculating intergenic regions...
[OSError] 28
  File "/home/skgthab/programs/iCount2/iCount-master/iCount/cli.py", line
437, in main
    result_object = func(**args)

  File
"/home/skgthab/programs/iCount2/iCount-master/iCount/genomes/segment.py",
line 728, in get_regions
    intergenic_neg = _complement(gtf.fn, fai, '-')

  File
"/home/skgthab/programs/iCount2/iCount-master/iCount/genomes/segment.py",
line 518, in _complement
    gtf_sorted = gtf_strand_only.sort(faidx=genome_file).saveas()

  File
"/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/bedtool.py",
line 775, in decorated
    result = method(self, *args, **kwargs)

  File
"/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/bedtool.py",
line 2908, in saveas
    compressed=compressed)

  File
"/home/skgthab/programs/ENV/lib/python3.5/site-packages/pybedtools-0.7.8-py3.5-linux-x86_64.egg/pybedtools/bedtool.py",
line 1211, in _collapse
    out_.writelines(in_)

Thank you!
best,
Nejc

**Comment by JureZmrzlikar** [comment]
I am not sure, but this is worth trying... pybedtools, python package that we use to handle bedtools-like operations also uses temporary directory (which is by default `/tmp`). You can change it with this command:
https://daler.github.io/pybedtools/autodocs/pybedtools.helpers.set_tempdir.html#pybedtools.helpers.set_tempdir

So, insert the following two lines in the iCount/iCount/__init__.py:
`import pybedtools` (line 21, after importing os)
`pybedtools.helpers.set_tempdir(TMP_ROOT)` (line 44, directly after TMP_ROOT is defined)

Let me know if it solves the issue.

**Comment by nebo56** [comment]
It works! Thanks Jure

**Comment by JureZmrzlikar** [comment]
Cool, great to hear this. Will make a PR with fix.
