### ISSUE TITLE
STAR index

### ISSUE THREAD

**Issue by Faitero** [tomazc/iCount#127]
On the manual is said `iCount mapindex ` but this instructions is not recognised by iCount. Need to be changed to `iCount indexstar`
`
iCount mapindex mus_musculus.84.chr10.fa.gz mm84 --annotation mus_musculus.84.gtf.gz
usage: iCount [-h] [-v]   ...
iCount: error: argument  : invalid choice: 'mapindex' (choose from 'releases', 'species', 'annotation', 'genome', 'segment', 'demultiplex', 'cutadapt', 'indexstar', 'mapstar', 'xlsites', 'annotate', 'clusters', 'group', 'peaks', 'rnamaps', 'summary', 'examples', 'man', 'args')
`

**Comment by JureZmrzlikar** [comment]
You're right, thanks for noticing. Will fix.
