### ISSUE TITLE
iCount mapstar do not accept "--runThreadN" comand

### ISSUE THREAD

**Issue by Faitero** [tomazc/iCount#131]
```
iCount mapstar extracted/exp_NNNTTGTNN.fastq.gz ../star_index/hg19_ensembl75 mappings/exp_NNNTTGTNN --runThreadN 1 --multimax 50 --mismatches 2 --annotation ../iCount_genomes/hs75.gtf.gz
usage: iCount [-h] [-v]   ...
iCount: error: unrecognized arguments: --runThreadN 1
```

**Comment by JureZmrzlikar** [comment]
Solution: use `--threads` instead.

Why? Use `iCount mapstar -h` and read **all** output. First part is (sadly) the technical description of how we call STAR inside the function. We use `--runThreadN` there. The last part of `iCount mapstar -h` describes what are the parameters for the `mapstar` command - you will se that threads (and other) optional parameters are listed there.

We need to improve the documentation...

**Comment by tomazc** [comment]
@JureZmrzlikar, please, solve this issue by pointing to the nicer documentation in [iCount/externals/star.py](https://github.com/tomazc/iCount/blob/master/iCount/externals/star.py#L135)
