### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by raflynn** [tomazc/iCount#155]
When I try to run "pip install icount" pip is unable to find the package.. Unfortunately, I can't use Docker on my cluster so I'm limited to a pip-type of install..

**Comment by JureZmrzlikar** [comment]
Hi @raflynn !

Unfortunately, iCount is not yet publishen on pypi - official python repository from where `pip install` command would be able to fetch it. Instead, you can use git to get the source code. Navigate to a directory, where you would like the package to be installed an then:

`git clone https://github.com/tomazc/iCount`
`cd iCount`
`pip install -e .` (note the dot at the end of command!)

And iCount is installed!

You can check list of available commands by typing:
`iCount --help`
Help is also available for each individual command, for example:
`iCount peaks --help`

Hope it works!

**Comment by raflynn** [comment]
Thanks, that worked!
