### ISSUE TITLE
Error while running iCount peaks

### ISSUE THREAD

**Issue by raflynn** [tomazc/iCount#164]
Hi all,
I downloaded the updated iCount this week and after installing it, I tried to run the peaks tool. Unfortunately I got a number of errors that I don't really understand. Any help figuring out what is happening would be much appreciated. The command I used and the resulting error is below.

[raflynn /home/groups/software2.0]$ iCount peaks --scores scores_out --features gene -g gene_id -prog /home/groups/software2.0/iCount_HOMER/gencode.v21.annotation.segment.gtf /home/groups/software2.0/test.bed /home/groups/software2.0/test_peaks.bed
/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/subprocess.py:761: ResourceWarning: subprocess 36915 is still running
  ResourceWarning, source=self)
/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/pybedtools/helpers.py:209: ResourceWarning: unclosed file <_io.BufferedReader name=4>
  _check_for_bedtools()
/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/pybedtools/helpers.py:209: ResourceWarning: unclosed file <_io.BufferedReader name=6>
  _check_for_bedtools()
/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/cli.py:428: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/groups/software2.0/iCount.log' mode='a' encoding='UTF-8'>
  logger.log_to_file(is_on=is_on, level=file_loglevel, path=file_logpath)
Executing the following command: iCount peaks --scores scores_out --features gene -g gene_id -prog /home/groups/software2.0/iCount_HOMER/gencode.v21.annotation.segment.gtf /home/groups/software2.0/test.bed /home/groups/software2.0/test_peaks.bed
Input parameters for function 'run' in iCount.analysis.peaks
    annotation: /home/groups/software2.0/iCount_HOMER/gencode.v21.annotation.segment.gtf
    sites: /home/groups/software2.0/test.bed
    peaks: /home/groups/software2.0/test_peaks.bed
    scores: scores_out
    features: ['gene']
    group_by: gene_id
    merge_features: False
    half_window: 3
    fdr: 0.05
    perms: 100
    rnd_seed: 42
    report_progress: True

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/cli.py", line 436, in main
    result_object = func(**args)
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/analysis/peaks.py", line 442, in run
    assert scores.endswith(('.tsv', '.tsv.gz', '.csv', '.csv.gz', 'txt', 'txt.gz'))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/bin/iCount", line 11, in <module>
    load_entry_point('iCount==2.0.1.dev0', 'console_scripts', 'iCount')()
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/cli.py", line 444, in main
    exception_message = exception.args[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/cli.py", line 436, in main
    result_object = func(**args)
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/analysis/peaks.py", line 442, in run
    assert scores.endswith(('.tsv', '.tsv.gz', '.csv', '.csv.gz', 'txt', 'txt.gz'))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/bin/iCount", line 11, in <module>
    load_entry_point('iCount==2.0.1.dev0', 'console_scripts', 'iCount')()
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount-2.0.1.dev0-py3.6.egg/iCount/cli.py", line 444, in main
    exception_message = exception.args[0]
IndexError: tuple index out of range

**Comment by raflynn** [comment]
I fixed a few things in my python, so there are no longer the warnings, but the tuple and AssertionError keep coming up, which seems specific to iCount (see below). I'm not sure how to address these.

Executing the following command: iCount peaks /home/groups/software2.0/iCount_HOMER/gencode.v21.annotation.segment.gtf /scratch/users/raflynn/analysis/fasticlip_results/HS_RBP/todelete/H
S_RBP_threshold=3_GRCh38_allreads.mergedRT_snoRNAremoved_miRNAremoved.bed /scratch/users/raflynn/analysis/fasticlip_results/HS_RBP/bedfiles/HS_RBP_iCountPeaks.bed --scores /scra
tch/users/raflynn/analysis/fasticlip_results/HS_RBP/bedfiles/HS_RBP_iCountPeaks_scores.tsv
Input parameters for function 'run' in iCount.analysis.peaks
    annotation: /home/groups/software2.0/iCount_HOMER/gencode.v21.annotation.segment.gtf
    sites: /scratch/users/raflynn/analysis/fasticlip_results/HS_RBP/todelete/HS_RBP_threshold=3_GRCh38_allreads.mergedRT_snoRNAremoved_miRNAremoved.bed
    peaks: /scratch/users/raflynn/analysis/fasticlip_results/HS_RBP/bedfiles/HS_RBP_iCountPeaks.bed
    scores: /scratch/users/raflynn/analysis/fasticlip_results/HS_RBP/bedfiles/HS_RBP_iCountPeaks_scores.tsv
    features: None
    group_by: gene_id
    merge_features: False
    half_window: 3
    fdr: 0.05
    perms: 100
    rnd_seed: 42
    report_progress: False
Loading annotation file...
60155 out of 2581788 annotation records will be used (2521633 skipped).
Loading cross-links file...
Calculating intersection between annotation and cross-link file...
Processing intersections...

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/cli.py", line 436, in main
    result_object = func(**args)
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/analysis/peaks.py", line 485, in run
    assert site_dot == '.'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/bin/iCount", line 11, in <module>
    load_entry_point('iCount==2.0.0', 'console_scripts', 'iCount')()
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/cli.py", line 444, in main
    exception_message = exception.args[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/cli.py", line 436, in main
    result_object = func(**args)
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/analysis/peaks.py", line 485, in run
    assert site_dot == '.'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/groups/software2.0/Pythonv3.6.2/bin/iCount", line 11, in <module>
    load_entry_point('iCount==2.0.0', 'console_scripts', 'iCount')()
  File "/home/groups/software2.0/Pythonv3.6.2/lib/python3.6/site-packages/iCount/cli.py", line 444, in main
    exception_message = exception.args[0]
IndexError: tuple index out of range

**Comment by JureZmrzlikar** [comment]
`sites` input should be result of `iCount xlsites` command (more precisely, it should be `sites_unique` file). Is this true in your case? If not, which file did you use and why?

**Comment by raflynn** [comment]
I see. I think I made an upstream error for the input, sorry for the trouble. I'll go back to some of the earlier steps and see if that fixes it. Thanks!

**Comment by raflynn** [comment]
Looking a bit more into the documentation it seems like, as you noted, the peaks tool uses a BED file generated from the xlsites tool. If I have a different way to isolate x-linked sites (RT stops), is there an example output of xlsites that I could see so that I can format my RT stop BED file properly for the peaks tool to use?

**Comment by JureZmrzlikar** [comment]
Output of xlsites is a normal BED (BED6) file.
col1: chromosome number
col2: start position
col3: end position (since crosslink site is always 1 nucleotide long, this i always start position +1)
col4: name (in our case we demand that name is `.`) @tomazc , this was your design choice why is that?
col5: score: number of crosslink events ()
col6: strand

**Comment by raflynn** [comment]
Thanks for the details. Giving it the correct input has seemingly solved the issue. knowing about the "." was very important. Thanks!
