### ISSUE TITLE
Suggest: '--genomeLoad', 'LoadAndRemove' for STAR

### ISSUE THREAD

**Issue by bakerwm** [tomazc/iCount#169]
If I have multiple samples to run mapping in parallel, I could use `--genomeLoad LoadAndKeep` to save memory by sharing the index in memory.

How about changing the following parameter in `star.py`?

The default:
```
--genomeLoad NoSharedMemory
do not use shared memory, each job will have its own private copy of the genome
```

Adjust:

```
--genomeLoad LoadAndRemove
load genome into shared but remove it after run
```

**Comment by JureZmrzlikar** [comment]
Good point. Would you be able to make a PR with suggested change?

**Comment by bakerwm** [comment]
ok, I will try to make a PR. @JureZmrzlikar

**Comment by bakerwm** [comment]
Please check the PR #170 . I added two lines in `star.py` @JureZmrzlikar
