### ISSUE TITLE
iCount clusters fails to predict clusters with bedtools 2.27 - no error or warning

### ISSUE THREAD

**Issue by mirax87** [tomazc/iCount#174]
`iCount clusters` reports no peak cluster at all with bedtools 2.27, whereas with bedtools 2.26 provides peak clusters. 

It seems like, this is due to that `iCount clusters` requires the `bedtools merge` output to report the strand. However, bedtools 2.27 does not report the strand after merging by default, one has to state it explicitly. In bedtools 2.26, the strand was reported by default.

Bedtools documentation - http://bedtools.readthedocs.io/en/latest/content/tools/merge.html

**Comment by JureZmrzlikar** [comment]
This is no true. Strand is not reported by defualt, not it `2.26`, neither in `2.27`. Could you provide more details in what cases it fails, some input files, stack trace, expected vs. observed bahaviour/output... Anything we could use to reproduce it.

**Comment by JureZmrzlikar** [comment]
Agh... i'm so sorry, i misunderstood your point, your're right! Will investigate this!

**Comment by Imoteph** [comment]
Hi, 

I can as well conform to hit the same issue using bedtools 2.7. With bedtools 2.26 I could get the cluster file. @mirax87 thx for the tip
