### ISSUE TITLE
trouble understanding the cDNA % in the summary gene report

### ISSUE THREAD

**Issue by YannAudic** [tomazc/iCount#176]
Hi,
I am trying/using iCount 
`Docker version 17.12.0-ce, build c97c6d6
docker run -i -t -v /mnt/Genome:/home/icuser/storage/Genome -v /mnt/Results:/home/icuser/storage/Results  tomazc/icount`

for processing iCLIP reads on the mouse genome (mm88). Thank you for this convenient tool.
However, I have problem to completely understand the results of the summary tool. For example for the  gene template, the computation of the cDNA % is hard to understand as from the python script I understand that the value of cDNA % is computed as
`line = ['{} ({})'.format(gene_name, gene_id), length, math.floor(cdna), cdna / sum_cdna * 100]`
where sum_cdna is (from what I understand) a constant computed from the xlsites bed file. 
`  for seg in BedTool(sites):
      sum_cdna += int(seg.score)
`
However, when I compute the cDNA_count / cDNA_% value for each gene, the result is not constant...

Am I missing something ?

I understand also that the sum of all the cDNA % could be > 100 % as some cDNA are used on multiple gene when they overlap.

Thank you 
Yann

**Comment by JureZmrzlikar** [comment]
What annotation are you using for the summary calculation? If you are using `mm88`, there are multiple genes/transcripts overlapping... You are supposed to run `iCount segment` on your annotation file and then use `regions.bed.gz` annotation file as input for summary. This is a "flattened" version of annotation, where there are no overlaps: if two genes overlap, the longer one is taken.

**Comment by YannAudic** [comment]
I am indeed using the segmented annotation obtained through 
`iCount annotation --source ensembl -od ${genome_dir} mus_musculus 88
iCount segment -prog ${genome_dir}/mus_musculus.88.gtf.gz ${genome_dir}/mm88seg.gtf.gz ${genome_dir}/mus_musculus.88.fa.gz.fai`

but this is not a bed file as  `regions.bed.gz` but a `gtf`

Then after using `xlsites` on my my treated bam files I compute the summary with 

`sites="/home/icuser/storage/Results/iClip_Xtalin/xlsites_fullbam/NNNTTGTNN_xlinkedsites_cDNA_unique.bed"
seg_annot="${genome_dir}/mm88seg.gtf.gz"
out_dir="/home/icuser/storage/Results/iClip_Xtalin/xlsites_fullbam/"
iCount summary ${seg_annot} ${sites} ${out_dir}`
#ALL_summary_gene.tsv
#ALL_summary_subtype.tsv
#ALL_summary_type.tsv

**Comment by JureZmrzlikar** [comment]
OK, got it. You already noticed, that `iCount segment` produces 5 files:

- `segmentation.gtf.gz`
- `regions.bed.gz` (which is in a GTF file, as you pointed out. This is error on our side, will fix it.)
- 3 template files

For summay, you should use `regios.gtf.gz` instead `segment.gtf.gz`. In this file, even transcripts/genes do not intersect and the ration `cDNA_count / cDNA_%` should be constant.

Thanks for spotting the typo!

**Comment by YannAudic** [comment]
thanks for the precisions,
yann
