### ISSUE TITLE
[E::bgzf_flush] File write failed (wrong size)

### ISSUE THREAD

**Issue by sbcrg** [tomazc/iCount#180]
Hi,

I am using the docker image for iCount; it works well expect for one of my bam files which is, I think, too big. 

I launch the container this way:
docker run -i -t -v ~/myproject/icount/storage_docker:/home/icuser/storage_docker -it tomazc/icount 

It fails with the xlsites command:
	iCount xlsites storage_docker/sample1.bam \
	sample1_cDNA_unique.bed sample1_cDNA_multiple.bed sample1_cDNA_skipped.bam \
	--group_by start --quant cDNA

I get the following error (even when I restart a new image after cleaning up the mounted volume):
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
[SamtoolsError] samtools returned with error 1: stdout=, stderr=
  File "/home/icuser/iCount_src/iCount/cli.py", line 439, in main
    result_object = func(**args)

  File "/home/icuser/iCount_src/iCount/mapping/xlsites.py", line 708, in run
    bam, metrics, mapq_th, skipped, segmentation, gap_th):

  File "/home/icuser/iCount_src/iCount/mapping/xlsites.py", line 561, in _processs_bam_file
    pysam.sort('-o', tmp_file, bam_fname)  # pylint: disable=no-member

  File "/home/icuser/.icountenv/lib/python3.4/site-packages/pysam/utils.py", line 75, in __call__
    stderr))

As it works well with smaller files (this bam file has over 400,000,000 entries), I think it might just be too large.
Do you have any solution/work around, or should I just consider splitting the data by chromosomes?

Many thanks!

**Comment by JureZmrzlikar** [comment]
Hi Sarah,

I'm not an expert regarding Docker, but consider [this](https://stackoverflow.com/questions/40621886/when-does-a-running-docker-container-run-out-of-disk-space): "container and local volume storage is limited by the underlying file system hosting `/var/lib/docker` and it's subdirectories" 

So, cleaning up disk space on your machine on the partition where your `/var/lib/docker` is located would be a thing to try...

**Comment by sbcrg** [comment]
Thanks! As I'm not root under that system, I can't do much about it myself. I'll comment it to the sys admin  and meanwhile I guess I'll give splitting the bam by chromosome a try :-)
