### ISSUE TITLE
SyntaxError Invalid syntax

### ISSUE THREAD

**Issue by krutru** [tomazc/iCount#183]
![screen shot 2018-06-26 at 12 20 21](https://user-images.githubusercontent.com/35422752/41913631-c06fc248-7948-11e8-973e-83946899d212.png)

Can someone please advice why I am seeing this error?

**Comment by JureZmrzlikar** [comment]
You are using Python2, which is not supported anymore. Please, use Python 3.5 or higher.

**Comment by krutru** [comment]
thank you JureZmrzlikar.

For anyone else wondering how to install and get it to work. On CentOS 7:

1.       Install python 3.6
     a.       sudo yum install https://centos7.iuscommunity.org/ius-release.rpm
     b.       sudo yum install python36u
2.       Install pip and dev packages
     a.       sudo yum install python36u-pip
     b.       sudo yum install python36u-devel
3.       Clone iCount
     a.       Git clone https://github.com/tomazc/iCount
4.       Install iCount
     a.       cd iCount
     b.       sudo python3.6 setup.py install
