### ISSUE TITLE
iCount clusters: error

### ISSUE THREAD

**Issue by tianxiahuihui** [tomazc/iCount#201]
Dear Sir:

Hello, your software seems change a lot, and I meet a error like this. But in your documentions, the example code is the same as me.
iCount clusters peaks.bed clusters.bed

![图片](https://user-images.githubusercontent.com/7579889/86512808-d8eb4f00-be37-11ea-976b-1ddcc2ad00f1.png)

Could you tell me what the three file is?

Thank you

**Comment by Faitero** [comment]
Dear Denghui330,

Clusters command should have at least three positional parameters, crosslink sites, significant sites and output clusters name:
`iCount clusters {input.xlsites} {input.sig_xlsites} {output.clusters}`

Best

**Comment by tianxiahuihui** [comment]
Dear Sir:

Maybe your documentation need to be changed. It shows "iCount clusters peaks.bed clusters.bed"

Thank you.
