### ISSUE TITLE
Clusters command generates empty file

### ISSUE THREAD

**Issue by JulieCremaschi** [tomazc/iCount#202]
Hi,

I am trying iCount with _D. melanogaster_ iCLIP datasets. Our data are very exploratory and the pipeline runs with default parameters, cross-link sites are well identified and validated. But when I am using the command _clusters_, still with the default parameters, the output clusters.bed is empty. I do not have any error. I have tried different values but even with a large window the output remains desperately empty.

When I am loading my sites and peaks bed files in IGV and checking some genes of interest, there are cross-linked sites close enough for merging. So I am a bit lost with this step, maybe I have missed something in the documentation. I would appreciate some clarification about the clusterisation.

By the way, I noticed that the tutorial on the iCount website is not completed, the command in the tuto is : iCount clusters peaks.bed clusters.bed but actually the command is : iCount clusters sites.bed peaks.bed clusters.bed

Thanks for your time,

Cheers
Julie

**Comment by Faitero** [comment]
Dear Julie,

Thanks for using iCount and providing test files. Clusterization is a simple bedtools merging adjacent peaks into clusters and adding cross-links within them. [https://github.com/tomazc/iCount/blob/master/iCount/analysis/clusters.py](url)

I was able to obtain cluster with your data so it should be an issue with outdated pybedtools. Please upgrade your bedtools to the latest version.

```
(iCount_pipeline3) $ iCount clusters iCLIP2_cDNA_unique.bed peaks.bed clusters.bed
Executing the following command: iCount clusters iCLIP2_cDNA_unique.bed peaks.bed clusters.bed
Input parameters for function 'run' in iCount.analysis.clusters
    sites: iCLIP2_cDNA_unique.bed
    peaks: peaks.bed
    clusters: clusters.bed
    dist: 20
    slop: 3
Reading individual sites from iCLIP2_cDNA_unique.bed
Reading peaks from peaks.bed
Merging peaks to form clusters
Summing sites within identified clusters
Done. Results saved to: ~/Programs/temp_iCount/pybedtools.2we0zvnr.tmp
```

```
(iCount_pipeline3) $ head clusters.bed
2L	9945	9951	l(2)gl-FBgn0002121	5	-
2L	9995	10033	l(2)gl-FBgn0002121	18	-
2L	10056	10060	l(2)gl-FBgn0002121	5	-
2L	10099	10103	l(2)gl-FBgn0002121	4	-
2L	10173	10178	l(2)gl-FBgn0002121	6	-
2L	10482	10492	l(2)gl-FBgn0002121	7	-
2L	10553	10560	l(2)gl-FBgn0002121	5	-
2L	10902	10948	l(2)gl-FBgn0002121	22	-
```

FYI I also noted some discrepancies in chromosomes names between crosslink and peak files but this is not the main issue.

Best wishes

**Comment by JulieCremaschi** [comment]
Hi,

Thank you for the answer. 
I have checked the currently installed version of bedtools and it is already up to date :
```
.local/bin/bedtools --version
bedtools v2.29.1
```
I am using iCount 2.0.0 and pybedtools is also up to date (v0.8.1).

Maybe the issue comes from the fact that iCount is running on a cluster where I don't have root privileges, only a user access. But it is weird that this step _failed_ when everything before worked properly.

Regards,
Julie

**Comment by Faitero** [comment]
Hi Julie,

iCount is suited to any environment even without root privileges. 

Did you define a temporal folder to save intermediate data? 
```
vi iCount/iCount/__init__.py
Change the following line:
TMP_ROOT = os.environ.get('ICOUNT_TMP_ROOT', 'a directory you have access to')
```

Let me know if this solves the issue

**Comment by JulieCremaschi** [comment]
I just defined one but it did not solve the issue.

**Comment by JulieCremaschi** [comment]
Fixed after reinstall iCount under conda environment.

Thank you very much for the help.
