### ISSUE TITLE
Application of iCount in Arabidopsis (plants) causes errors.

### ISSUE THREAD

**Issue by Linhua-Sun** [tomazc/iCount#205]
Hi: 
I am trying to apply iCount into the analysis of Arabidopsis CLIP-Seq. But a lot of problems came. As shown in the web: `Command segment can read the annotation obtained from ensembl and generate a new annotation file with genome segmentation`. However, there is no annotation for Arabidopsis in ensembl. Plants have their own annotation in website like ftp://ftp.ensemblgenomes.org/pub/plants/release-48/gtf/arabidopsis_thaliana . Is it possibile to apply `segment` in Arabidopsis gtf. I have tried it, but it failed. I also tried the software in human's successfully. Thanks!

```
iCount segment Arabidopsis_thaliana.TAIR10.48.gtf Arabidopsis_thaliana.TAIR10.48.seg.gtf NoChrNucTAIR10.fa.fai
Executing the following command: iCount segment Arabidopsis_thaliana.TAIR10.48.gtf Arabidopsis_thaliana.TAIR10.48.seg.gtf NoChrNucTAIR10.fa.fai
Input parameters for function 'get_regions' in iCount.genomes.segment
    annotation: Arabidopsis_thaliana.TAIR10.48.gtf
    segmentation: Arabidopsis_thaliana.TAIR10.48.seg.gtf
    fai: NoChrNucTAIR10.fa.fai
    report_progress: False
[ValueError] need more than 1 value to unpack
  File "/Users/sunlinhua/miniconda2/envs/hic/lib/python3.6/site-packages/iCount/cli.py", line 436, in main
    result_object = func(**args)

  File "/Users/sunlinhua/miniconda2/envs/hic/lib/python3.6/site-packages/iCount/genomes/segment.py", line 723, in get_regions
    for gene_content in _get_gene_content(annotation, chromosomes, report_progress):

  File "/Users/sunlinhua/miniconda2/envs/hic/lib/python3.6/site-packages/iCount/genomes/segment.py", line 610, in _get_gene_content
    if interval.attrs['gene_id'] == current_gene:

  File "pybedtools/cbedtools.pyx", line 392, in pybedtools.cbedtools.Interval.attrs.__get__

  File "pybedtools/cbedtools.pyx", line 180, in pybedtools.cbedtools.Attributes.__init__
```

**Comment by Faitero** [comment]
Dear @Linhua-Sun,

Thanks for using iCount. We have foreseen the use of many genome annotations but up to now, we haven't tried Arabidopsis_thaliana genome. After exhaustive exploration of your issue, I found that the 9th column of your gtf files contains errors. We benefit from pybedtools to parse and extract fields as "gene_name". Pybedtools uses ";" to split terms and unfortunately in ENSEMBL Arabidopsis_thaliana annotation, semicolon ";" appears as part of "gene_name1;3" in several genes:

CYCB3;1
PHO1;H3
PHT1;8
SULTR1;3
SULTR3;3
CYCB1;5
GGCT2;3
CYCB2;4
SULTR2;2
SULTR1;2
SULTR2;1
SULTR4;1
SULTR3;5
PHT4;5
GGCT2;1
CYCH;1
NIP4;2
NAP1;3
CYCD4;1
SIP2;1

Although I check that those are the official names it mess up with pybedtools and `iCount segment` parsing. We will try to include this exception on next iCount version but for now, you can substitute ";" with "_" using below code:

`cat Arabidopsis_thaliana.TAIR10.48.gtf | sed 's/\GGCT\([0-9]\)\;\([0-9]\)/GGCT\1\_\2/g' | sed 's/\CYCB\([0-9]\)\;\([0-9]\)/CYCB\1\_\2/g' | sed 's/\PHO\([0-9]\)\;H\([0-9]\)/PHO\1\_H\2/g' | sed 's/\PHT\([0-9]\)\;\([0-9]\)/PHT\1\_\2/g' | sed 's/\SULTR\([0-9]\)\;\([0-9]\)/SULTR\1\_\2/g' | sed 's/\CYCH\;\([0-9]\)/SULTR\_\1/g' | sed 's/\NIP\([0-9]\)\;\([0-9]\)/NIP\1\_\2/g' | sed 's/\NAP\([0-9]\)\;\([0-9]\)/NAP\1\_\2/g' | sed 's/\CYCD\([0-9]\)\;\([0-9]\)/CYCD\1\_\2/g' | sed 's/\SIP\([0-9]\)\;\([0-9]\)/SIP\1\_\2/g' > Arabidopsis_thaliana.TAIR10.48.modify.gtf`

Then point to this newly generated gtf "Arabidopsis_thaliana.TAIR10.48.modify.gtf" when calling `iCount segment`. After the substitution, I tryied the whole iCount pipeline with test data and Arabidopsis annotation without errors.

Let me know if this solves your problem.

Best

**Comment by Linhua-Sun** [comment]
That's great. Thank you very much for your reply. I'm sorry to see it so long
